// GENERATED by tools/gen-types.mjs — do not edit by hand.
//
// Names and ARITY come from the source and cannot drift from it: `npm run types` regenerates, and
// `types-parity-gate` fails when a declaration and its export disagree. Value types are `unknown`
// where nobody has refined them yet — a complete loose declaration beats a precise stale one, which
// is the defect this file exists to prevent (#105).
// Package: @ust-protocol/mcp

export function dispatch(name: unknown, args?: unknown): Promise<{ isError: unknown; error: unknown }>;
export function listTools(): Record<string, unknown>;
export const productTools: unknown;
export const tools: unknown;
