// GENERATED by tools/gen-types.mjs — do not edit by hand.
//
// Names and ARITY come from the source and cannot drift from it: `npm run types` regenerates, and
// `types-parity-gate` fails when a declaration and its export disagree. Value types are `unknown`
// where nobody has refined them yet — a complete loose declaration beats a precise stale one, which
// is the defect this file exists to prevent (#105).
//
// WHAT `unknown` MEANS HERE (#117). It is a promise we are NOT making, never a generator that gave up:
// this file is derived from a JavaScript body, and a shape it cannot prove is left for you to narrow
// rather than asserted. Narrowing costs a type guard and the compiler then proves the result; a
// confident wrong type costs you a crash. Two return types WERE confidently wrong and are now honest
// `unknown` — that direction is the fix, not a regression.
//
// The three shapes below are the exception, because a consumer cannot avoid them and because they are
// MEASURED from real values this suite builds, not read off the specification. A gate rebuilds those
// values and fails if a declared key is missing, so they cannot drift into being the stale kind.
// Package: @ust-protocol/cli

export function addKeylogKey(arg0?: unknown): Promise<{ keylog: unknown; newKey: unknown }>;
export const ARTIFACT_ORIGIN: Readonly<{ genesis: 'loaded'; keylog: 'loaded'; cadence: 'loaded'; witness: 'derived' }>;
export function askHidden(q: unknown, fallbackAsk: unknown): Promise<string>;
export function attestDiscovery(arg0?: unknown): Promise<{ hash: unknown; checks: unknown; verdict: unknown }>;
export function attestMirror(arg0?: unknown): Promise<{ canonHash: unknown; results: unknown; failed: unknown }>;
export function buildCeremony(arg0?: unknown): Promise<{ genesis: unknown; keylog0: unknown; genHash: unknown; op: unknown; opPkcs8: unknown; pkcs8: unknown; warnings: unknown }>;
export function buildWitnessLog(genesisText: unknown, anchors?: unknown, priorLogText?: unknown): unknown;
export function buildWorkerScript(genesisText: unknown, keylogText?: unknown, witnessText?: unknown, cadenceText?: unknown): string;
export function buildWranglerProject(arg0?: unknown): Record<string, unknown>;
export const CEREMONY_STEPS: unknown;
export function ceremonyMap(current?: unknown): unknown;
export function ceremonySummary(arg0?: unknown): unknown[];
export const CF_DNS_TOKEN_URL: unknown;
export function cfApexSteps(arg0?: unknown): Promise<{ zoneId: unknown; proxied: unknown; flipped: unknown; warnings: unknown }>;
export function cfPublish(arg0?: unknown): Promise<{ genHash: unknown; script: unknown; route: unknown; routeAction: unknown; proxied: unknown; flipped: unknown; warnings: unknown }>;
export function cfUpsert(arg0?: unknown): Promise<{ action: unknown }>;
export function checkPublished(liveText: unknown, genHash: unknown): unknown;
export function closeReader(rl: unknown): unknown;
export function cmdCadence(): Promise<unknown>;
export function cmdRotate(): Promise<string>;
export function collectServed(arg0?: unknown): Promise<{ genesisText: unknown; keylogText: unknown; cadenceText: unknown; witnessText: unknown }>;
export function confirmLive(arg0?: unknown): Promise<unknown>;
export function contextFor(doc?: unknown): boolean;
export function decodeInput(raw: unknown): unknown;
export function decryptKey(b64: unknown, pass: unknown): unknown;
export const DERIVED_REQUIRES_PRIOR: unknown;
export const DISCOVERY_ARTIFACTS: unknown;
export function dohConfirmTxt(arg0?: unknown): Promise<Record<string, unknown>>;
export function encryptKey(pkcs8: unknown, pass: unknown): string;
export const FORKCHOICE_BOOL_FLAGS: unknown;
export const FORKCHOICE_VALUE_FLAGS: unknown;
export const GOLD_REFUSAL: unknown;
export function invocation(): unknown;
export function logToRekor(rootHex: unknown, arg1?: unknown): Promise<{ substrate: unknown; logIndex: unknown; body: unknown; inclusionProof: unknown; integratedTime: unknown }>;
export function manualDnsGuide(domain: unknown, txt: unknown): unknown[];
export function manualServingGuide(domain: unknown, outDir: unknown): unknown[];
export function offlineHandoff(arg0: unknown): unknown[];
export function openReader(createInterface: unknown): unknown;
export function parseKeylogRaw(raw: unknown): unknown;
export function parseLogRaw(raw: unknown, label?: unknown): unknown;
export function positionals(argv: unknown, valueFlags: unknown): unknown;
export function rawTextOf(raw: unknown): { verdict: unknown; doc: unknown; text: unknown };
export function remintProbe(arg0?: unknown): Promise<unknown>;
export const RESERVED_TEST_NAME: unknown;
export function rootSignerFrom(pkcs8: unknown, rootPubB64url: unknown): Promise<unknown>;
export function rotateKeylog(arg0?: unknown): Promise<{ keylog: unknown; newOp: unknown; supersededKeyId: unknown; revokedPub: unknown }>;
export function scanDupes(text: unknown): string;
export function selfHostedPlan(arg0: unknown): unknown[];
export function servedArtifacts(arg0?: unknown): unknown;
export function stageSummary(arg0?: unknown): unknown[];
export const STREAM_VALUE_FLAGS: unknown;
export function validateKeylogChain(genesisDoc: unknown, entries: unknown): string;
export function validatePublishInputs(arg0?: unknown): { doc: unknown; genHash: unknown; entries: unknown };
export function verdictOf(checks: unknown): string;
export function verifyRaw(raw: unknown, opts?: unknown): unknown;
export function whatsNextSummary(arg0?: unknown): unknown[];
export const WRANGLER_LOGIN_CMD: unknown;
export function wranglerDeploy(arg0?: unknown): Promise<{ genHash: unknown; script: unknown; route: unknown; dir: unknown }>;
export const ghMirrorPublish: unknown;
