// GENERATED by tools/gen-types.mjs — do not edit by hand.
//
// Names and ARITY come from the source and cannot drift from it: `npm run types` regenerates, and
// `types-parity-gate` fails when a declaration and its export disagree. Value types are `unknown`
// where nobody has refined them yet — a complete loose declaration beats a precise stale one, which
// is the defect this file exists to prevent (#105).
// Package: @ust-protocol/ots-verify

export function makeSubstrateVerify(arg0?: unknown): unknown;
export function parseOtsBitcoin(ots: unknown): unknown;
export const substrateVerify: unknown;
export function toVerifiedEvidence(subject: unknown, result?: unknown, source_id?: unknown): { proof_kind: unknown; subject: unknown; source_id: unknown; facts: unknown };
