// GENERATED by tools/gen-types.mjs — do not edit by hand.
//
// Names and ARITY come from the source and cannot drift from it: `npm run types` regenerates, and
// `types-parity-gate` fails when a declaration and its export disagree. Value types are `unknown`
// where nobody has refined them yet — a complete loose declaration beats a precise stale one, which
// is the defect this file exists to prevent (#105).
//
// WHAT `unknown` MEANS HERE (#117). It is a promise we are NOT making, never a generator that gave up:
// this file is derived from a JavaScript body, and a shape it cannot prove is left for you to narrow
// rather than asserted. Narrowing costs a type guard and the compiler then proves the result; a
// confident wrong type costs you a crash. Two return types WERE confidently wrong and are now honest
// `unknown` — that direction is the fix, not a regression.
//
// The three shapes below are the exception, because a consumer cannot avoid them and because they are
// MEASURED from real values this suite builds, not read off the specification. A gate rebuilds those
// values and fails if a declared key is missing, so they cannot drift into being the stale kind.
// Package: ust-protocol

export interface UstState { id: Record<string, unknown>; time: unknown; data: unknown; hashes: unknown }
export interface UstDocument { ust: unknown; state: UstState; sig: unknown }
export interface UstVerdict { result: string; error: unknown; detail: unknown; tier: unknown; id?: unknown; publisher?: unknown; publisher_claimed?: unknown }

// A function with two OUTCOMES is a discriminated union, not an untypeable value. Saying "these are unions,
// so one interface would lie" and leaving them `unknown` was a substitution — TypeScript has unions, and the
// branches below were READ from real values: the resolved branch from a corpus key-log vector, the error
// branch from a rejected one. Discriminate on `error` in `res` and the compiler narrows for you.
export interface UstError { error: string; detail: unknown }
export interface UstKeysResolved { validKeys: unknown; active: unknown; revoked: unknown; history: unknown; roles: unknown; declaredRoles: unknown; head: string }
export type UstKeyResolution = UstKeysResolved | UstError;
export interface UstStreamComplete { complete: string; head?: unknown; detail?: unknown; interval?: unknown; reason?: unknown }
export type UstStreamVerdict = UstStreamComplete | UstError;

export function admitDeep(v: unknown, seen?: unknown): unknown;
export function admitUtf8(bytes: unknown): { err: unknown };
export function anchorRollup(arg0?: unknown): unknown;
export function anyLoneSurrogate(root: unknown): unknown;
export function assertValid(verdict: unknown): unknown;
export const ASSURANCE_AXES: unknown;
export function assuranceLE(a: unknown, b: unknown): unknown;
export function assuranceState(s?: unknown): unknown;
export function authorityCheckpointId(cp: unknown): string;
export function authorityScopeId(activeGenesis: unknown): string;
export function axisRank(axis: unknown, v: unknown): unknown;
export function blindedCommit(arg0: unknown): string;
export function blindPartition(name: unknown, value: unknown, arg2?: unknown): { partition: unknown; hash: unknown };
export function buildAbsence(id: unknown, time: unknown, name: unknown, reason: unknown, extra?: unknown, prev?: unknown): unknown;
export function buildAnchorCommitment(id: unknown, time: unknown, root: unknown, prev: unknown, anchor: unknown): Record<string, unknown>;
export function buildAttestation(id: unknown, time: unknown, data: unknown, constituents: unknown, prev?: unknown): Record<string, unknown>;
export function buildAuthorityCheckpoint(arg0?: unknown): { version: unknown; purpose: unknown; domain_shard: unknown; genesis_epoch: unknown; sequence: unknown; checkpoint_authority: unknown; keylog: unknown };
export function buildAuthorityProof(inputs?: unknown): { term: unknown; witnesses: unknown };
export function buildCadenceEntry(id: unknown, time: unknown, cadence: unknown, effectiveFrom: unknown, prev: unknown): unknown;
export const buildCheckpoint: unknown;
export function buildDerivation(id: unknown, time: unknown, data: unknown, basedOn: unknown, prev?: unknown): Record<string, unknown>;
export function buildEpochTransition(fields: unknown, privKeyObj: unknown, issuerPubB64url: unknown): { claim: unknown; issuer_id: unknown; sig: unknown };
export function buildEvidenceReceipt(fields: unknown, privKeyObj: unknown, issuerPubB64url: unknown): { claim: unknown; issuer_id: unknown; sig: unknown };
export function buildGap(id: unknown, time: unknown, prev: unknown, reason?: unknown): Record<string, unknown>;
export function buildGenesis(id: unknown, time: unknown, pub: unknown, maxPartitions?: unknown, maxTranscriptBytes?: unknown, cadence?: unknown, checkpointAuthority?: unknown, recovery?: unknown, roles?: unknown): Record<string, unknown>;
export function buildKeylogCommitment(entryHashes: unknown): unknown;
export function buildKeyLogEntry(id: unknown, time: unknown, keyOp: unknown, prev: unknown): Record<string, unknown>;
export function buildNoForkEvidence(fields: unknown, privKeyObj: unknown, issuerPubB64url: unknown): { claim: unknown; issuer_id: unknown; sig: unknown };
export function buildRecoveryStatement(fields: unknown, privKeyObj: unknown, issuerPubB64url: unknown): { claim: unknown; issuer_id: unknown; sig: unknown };
export function buildState(id: unknown, time: unknown, data: unknown, provenance: unknown, opts?: unknown): unknown;
export function buildStreamCheckpoint(id: unknown, time: unknown, head: unknown, frameCount: unknown, prev: unknown, interval?: unknown): Record<string, unknown>;
export function buildUniquenessAttestation(fields: unknown, privKeyObj: unknown, issuerPubB64url: unknown): { claim: unknown; issuer_id: unknown; sig: unknown };
export function buildVerifiableMap(leaves: unknown): unknown;
export function canon(v: unknown): string;
export function capAssurance(state: unknown, ceiling: unknown): Record<string, unknown>;
export function checkAuthorityProof(obj: unknown, config: unknown): { result: unknown; reason: unknown };
export function checkAuthorityProofBytes(packageBytes: unknown, configBytes: unknown): unknown;
export function checkBounds(rawDoc: unknown): string;
export function checkpointMapLeaf(arg0: unknown): unknown;
export function checkpointRecoveryClaim(arg0: unknown): { purpose: unknown; domain_shard: unknown; genesis_epoch: unknown; last_accepted_checkpoint: unknown; replacement_authority: unknown; effective_sequence: unknown };
export function checkpointUniquenessClaim(arg0: unknown): { purpose: unknown; domain_shard: unknown; genesis_epoch: unknown; sequence: unknown; checkpoint: unknown };
export function combineInclusion(verifiers: unknown): unknown;
export function combineSubstrates(verifiers: unknown): unknown;
export function compareEvidenceOrder(a: unknown, b: unknown): string;
export function contentHash(doc: unknown): string;
export function deriveAssurance(graph: unknown): unknown;
export function deriveCheckpointFreshness(chain: unknown, config: unknown): unknown;
export function edVerifyStrict(pubB64url: unknown, msgUtf8: unknown, sigB64url: unknown): unknown;
export function epochTransitionClaim(arg0?: unknown): { purpose: unknown; domain_shard: unknown; from_genesis_epoch: unknown; from_final_checkpoint: unknown; to_checkpoint_authority: unknown; to_initial_sequence: unknown };
export const EVIDENCE_CAPS_UNIVERSE: unknown;
export function evidenceCaps(proof_kind: unknown): unknown;
export function evidenceClass(proof_kind: unknown): string;
export function evidenceReceiptClaim(arg0?: unknown): { version: unknown; purpose: unknown; domain_shard: unknown; active_genesis: unknown; genesis_epoch: unknown; proof_kind: unknown; facts: unknown; issued_at: unknown };
export function evidenceReceiptId(r: unknown): string;
export function forkChoice(candidates: unknown, opts?: unknown): Promise<unknown>;
export function genesisEpoch(activeGenesis: unknown): string;
export function H(tag: unknown, strInput: unknown): unknown;
export function Hbytes(tag: unknown, rawBuf: unknown): unknown;
export function isPublicDnsShard(shard: unknown): unknown;
export function isValid(r: unknown): boolean;
export function isVerifiedHandle(kind: unknown, x: unknown): unknown;
export function joinAssurance(a: unknown, b: unknown): unknown;
export function keyId(pubB64url: unknown): unknown;
export function keylogLeaf(entryHash: unknown): string;
export function meetAssurance(a: unknown, b: unknown): unknown;
export function merkleRoot(contentHashes: unknown): unknown;
export function nameMapLeaf(arg0: unknown): unknown;
export function noEventBacking(claimWindow: unknown, streamResult: unknown, frames: unknown): string;
export function noForkClaim(arg0: unknown): { purpose: unknown; domain_shard: unknown; active_genesis: unknown };
export function parseCadenceInt(s: unknown): unknown;
export function partitionHash(arg0: unknown): unknown;
export const PREV_ONLY_SUBTYPES: readonly ['checkpoint', 'gap', 'anchor'];
export function projectTier(state: unknown): string;
export function provePredicates(seams?: unknown): unknown;
export function quorumTrustDomains(list: unknown, config: unknown): unknown;
export const REFERENCE_CHECKER_RULES: unknown;
export const REFERENCE_CHECKER_VERSION: unknown;
export const REGISTRY: unknown;
export function registryDigest(): unknown;
export function replicationAgreement(arg0?: unknown): unknown;
export function resolveAuthority(doc: unknown, opts?: unknown): unknown;
export function resolveByDiscovery(doc: unknown, opts?: unknown, transport?: unknown): Promise<{ verdict: unknown; resolution: unknown }>;
export function resolveCadence(genesis: unknown, cadenceLog?: unknown, atTime?: unknown, opts?: unknown): { error: unknown; detail: unknown };
export function resolveCadenceBytes(genesisBytes: unknown, cadenceLogBytes: unknown, atTime: unknown, keylogBytes: unknown): unknown;
export function resolveCheckpointRoots(genesis: unknown): unknown;
export function resolveKeys(genesis: unknown, keylog?: unknown): UstKeyResolution;
export function resolveKeysBytes(genesisBytes: unknown, keylogBytes: unknown): unknown;
export const RULE_CONTRACTS: unknown;
export function seal(state: unknown, privKeyObj: unknown, pubB64url: unknown): UstDocument;
export function sealAuthorityCheckpoint(body: unknown, privKeyObj: unknown, pubB64url: unknown): { body: unknown; sig: unknown };
export function seed(contentHashes: unknown): string;
export function signedContent(doc: unknown): string;
export function snapshotBytes(input: unknown, maxBytes?: unknown, sizeErr?: unknown): unknown;
export const STABILITY: Readonly<{ light: 'stable'; high: 'stable'; corroborated: 'experimental-usable'; attested: 'experimental-extension' }>;
export function strictB64url(s: unknown, bytes: unknown): string;
export function surfaceVerdict(arg0?: unknown): unknown;
export const TIER_RANK: unknown;
export function ustGrid(from: unknown, to: unknown, cadenceSec: unknown): unknown;
export class UstIndeterminate extends Error { constructor(verdict?: unknown); }
export class UstInvalid extends Error { constructor(verdict?: unknown); }
export function verifiedEvidence(arg0?: unknown): { proof_kind: unknown; subject: unknown; source_id: unknown; facts: unknown };
export function verifiedGenesisContext(genesis: unknown): unknown;
export function verify(doc: unknown, opts?: unknown): UstVerdict;
export function verifyActiveGenesisUniqueness(proof: unknown, config: unknown): unknown;
export function verifyAnchor(contentHash: unknown, proof: unknown, opts?: unknown): { inclusion: unknown; error: unknown; detail: unknown };
export function verifyAsync(doc: unknown, opts?: unknown): Promise<{ result: unknown; error: unknown; detail: unknown }>;
export function verifyAuthorityBundle(inputs?: unknown, config?: unknown): unknown;
export function verifyAuthorityCheckpointChain(chain: unknown, config: unknown): unknown;
export function verifyCheckpointMapUniqueness(proof: unknown, config: unknown): unknown;
export function verifyCheckpointRecovery(statements: unknown, config: unknown): unknown;
export function verifyCheckpointUniqueness(attestations: unknown, config: unknown): unknown;
export function verifyEpochTransition(statement: unknown, config: unknown): unknown;
export function verifyEvidenceReceipt(receipt: unknown, config: unknown): unknown;
export function verifyJson(rawBytes: unknown, opts?: unknown): UstVerdict;
export function verifyKeylogTerminality(head_: unknown, proof?: unknown): { terminal: unknown; detail: unknown };
export function verifyNoForkEvidence(evidence: unknown, config: unknown): unknown;
export function verifyOrThrow(doc: unknown, opts?: unknown): unknown;
export function verifyStream(frames: unknown, config: unknown): UstStreamVerdict;
export const VERSION: unknown;
export function witnessNoFork(shard: unknown, genesisHash: unknown, opts: unknown): Promise<unknown>;
export function witnessNoShrink(prior: unknown, next: unknown): string;
export function witnessSuccessor(prior: unknown, next: unknown): { error: unknown };
