// GENERATED by tools/gen-types.mjs — do not edit by hand.
//
// Names and ARITY come from the source and cannot drift from it: `npm run types` regenerates, and
// `types-parity-gate` fails when a declaration and its export disagree. Value types are `unknown`
// where nobody has refined them yet — a complete loose declaration beats a precise stale one, which
// is the defect this file exists to prevent (#105).
// Package: @ust-protocol/operator

export class AnchorBatch { constructor(verdict?: unknown); }
export function assembleLayers(layers: unknown, arg1?: unknown): { valid: unknown; seedOk: unknown; perLayer: unknown; verifiedDepth: unknown };
export const BREADTH: unknown;
export class KeyLog { constructor(verdict?: unknown); }
export function layerSeed(subordinateDocs: unknown): unknown;
export function sealLayerChain(outerState: unknown, subordinateDocs: unknown, sign: unknown): unknown;
export function sealTree(idMeta: unknown, time: unknown, hashes: unknown, sign: unknown, arg4?: unknown): Promise<unknown>;
export class Stream { constructor(verdict?: unknown); }
export const substrates: unknown;
export function substrateVerifier(deps?: unknown): unknown;
export class Tiers { constructor(verdict?: unknown); }
export function walkChain(doc: unknown, fetch: unknown, arg2?: unknown): Promise<unknown>;
