// GENERATED by tools/gen-types.mjs — do not edit by hand.
//
// Names and ARITY come from the source and cannot drift from it: `npm run types` regenerates, and
// `types-parity-gate` fails when a declaration and its export disagree. Value types are `unknown`
// where nobody has refined them yet — a complete loose declaration beats a precise stale one, which
// is the defect this file exists to prevent (#105).
//
// WHAT `unknown` MEANS HERE (#117). It is a promise we are NOT making, never a generator that gave up:
// this file is derived from a JavaScript body, and a shape it cannot prove is left for you to narrow
// rather than asserted. Narrowing costs a type guard and the compiler then proves the result; a
// confident wrong type costs you a crash. Two return types WERE confidently wrong and are now honest
// `unknown` — that direction is the fix, not a regression.
//
// The three shapes below are the exception, because a consumer cannot avoid them and because they are
// MEASURED from real values this suite builds, not read off the specification. A gate rebuilds those
// values and fails if a declared key is missing, so they cannot drift into being the stale kind.
// Package: @ust-protocol/operator

export function advanceHead(store: unknown, arg1?: unknown): Promise<string>;
export class AnchorBatch { constructor(verdict?: unknown); }
export function assembleLayers(layers: unknown, arg1?: unknown): { valid: unknown; seedOk: unknown; perLayer: unknown; verifiedDepth: unknown };
export const BREADTH: unknown;
export class KeyLog { constructor(verdict?: unknown); }
export function layerSeed(subordinateDocs: unknown): unknown;
export function loadStreamState(store: unknown): Promise<{ head: unknown; count: unknown; cpHead: unknown; spanFrom: unknown; spanTo: unknown }>;
export function memoryStore(): { get: unknown; set: unknown; del: unknown };
export function reconcileHead(store: unknown, arg1?: unknown): Promise<{ state: unknown; head: unknown }>;
export function recordCheckpoint(store: unknown, arg1: unknown): Promise<unknown>;
export function recordFrame(store: unknown, arg1?: unknown): Promise<{ guarantee: unknown; count: unknown }>;
export function recoverHead(store: unknown, arg1?: unknown): Promise<{ state: unknown; head: unknown }>;
export function sealLayerChain(outerState: unknown, subordinateDocs: unknown, sign: unknown): unknown;
export function sealTree(idMeta: unknown, time: unknown, hashes: unknown, sign: unknown, arg4?: unknown): Promise<unknown>;
export class Stream { constructor(verdict?: unknown); }
export const STREAM_KEYS: unknown;
export const substrates: unknown;
export function substrateVerifier(deps?: unknown): unknown;
export class Tiers { constructor(verdict?: unknown); }
export function walkChain(doc: unknown, fetch: unknown, arg2?: unknown): Promise<unknown>;
