// GENERATED by tools/gen-types.mjs — do not edit by hand.
//
// Names and ARITY come from the source and cannot drift from it: `npm run types` regenerates, and
// `types-parity-gate` fails when a declaration and its export disagree. Value types are `unknown`
// where nobody has refined them yet — a complete loose declaration beats a precise stale one, which
// is the defect this file exists to prevent (#105).
// Package: ust-light

export function buildState(id: unknown, time: unknown, data: unknown, provenance?: unknown): unknown;
export function canon(v: unknown): unknown;
export function contentHash(doc: unknown): unknown;
export function H(tag: unknown, str: unknown): unknown;
export function keyId(pubB64url: unknown): unknown;
export function keypair(): unknown;
export function seal(state: unknown, privateKey: unknown, pubB64url: unknown): unknown;
export function seed(contentHashes: unknown): unknown;
export function signedContent(doc: unknown): unknown;
export function verify(doc?: unknown): unknown;
